# Generated by Django 6.0.5 on 2026-06-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_skill_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='title',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_have',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_want',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
