# Generated by Django 6.0.5 on 2026-06-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_skill_title_skill_skill_have_skill_skill_want'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_have',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_want',
            field=models.CharField(max_length=100),
        ),
    ]
